# coding: utf-8

# flake8: noqa
"""
    sdk.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.agones_model.game_server_object_meta import GameServerObjectMeta
from swagger_client.agones_model.game_server_spec import GameServerSpec
from swagger_client.agones_model.game_server_status import GameServerStatus
from swagger_client.agones_model.protobuf_any import ProtobufAny
from swagger_client.agones_model.runtime_stream_error import RuntimeStreamError
from swagger_client.agones_model.sdk_duration import SdkDuration
from swagger_client.agones_model.sdk_empty import SdkEmpty
from swagger_client.agones_model.sdk_game_server import SdkGameServer
from swagger_client.agones_model.sdk_key_value import SdkKeyValue
from swagger_client.agones_model.spec_health import SpecHealth
from swagger_client.agones_model.status_player_status import StatusPlayerStatus
from swagger_client.agones_model.status_port import StatusPort
